name: "Quicksilver0218's Personal Site"
title: "Quicksilver0218's Personal Site"
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
  - jekyll-relative-links
minima:
  skin: dark
relative_links:
  enabled: true
  collections: true
include:
  - index.md
